# Copyright 2018 David Walter.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# docker build --no-cache --tag=debian-systemd .

# on ubuntu 17.04 default install with ext4 file system, aufs failed
# with kernel 4.13.0-12-generic, had to modify /etc/docker/daemon.json
# to use overlay2
# {
#   "storage-driver": "overlay2"
# }
# ------------------------------------------------------------------------
# container_linux.go:247: starting container process caused
# "process_linux.go:359: container init caused \"rootfs_linux.go:54:
# mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/docker/auf
# ------------------------------------------------------------------------

FROM {{ .DockerUser }}/{{.BaseImage}}
ENV init /lib/systemd/systemd
ENV container docker
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN echo 'APT::Install-Recommends "0"; \n\
    APT::Get::Assume-Yes "true"; \n\
    APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01buildconfig ; \
    mkdir -p  /etc/apt/sources.d/ ; \
    apt-get update && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN  apt-get -qq -y update; \
     apt-get -qq -y install --reinstall openssh-client openssh-server \
                    rsync git bash sudo ca-certificates \
                    inetutils-ping iproute2 nmap less; \
    mkdir -p /etc/ssh /var/run/sshd ; \
    apt -yq install locales; echo "LC_ALL=en_US.UTF-8" >> /etc/environment;  \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen ; \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf; \
    locale-gen en_US.UTF-8;

COPY entrypoint.sh /usr/bin/entrypoint.sh
COPY systemd-user-sessions.service /lib/systemd/system/systemd-user-sessions.service
# Moved to entrypoint.sh
# RUN systemctl set-default multi-user.target; systemctl default; systemctl isolate default.target

RUN  chmod +x /usr/bin/entrypoint.sh; \
     chmod 644 /lib/systemd/system/systemd-user-sessions.service

EXPOSE 22

VOLUME [ "/sys/fs/cgroup" ]
#CMD ["/usr/bin/entrypoint.sh"]
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

# local variables:
# mode: conf
# end:
